### ISSUE TITLE
Dependency on 'six' and 'past' modules cause ModuleNotFoundError in a fresh Python 3(.7.3) virtualenv

### ISSUE THREAD

**Issue by lestephane** [twang817/rubyenv#3]
In a freshly created Python v3.7.3 virtualenv where I installed rubyenv using

```text
pip install rubyenv
```

When running

```text
rubyenv install 2.4.2
```

I get the following error

```text
Traceback (most recent call last):
  File ".../.virtualenvs/.../bin/rubyenv", line 6, in <module>
    from rubyenv import main
  File ".../.virtualenvs/.../lib/python3.7/site-packages/rubyenv/__init__.py", line 1, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

Expected behaviour: `pip install rubyenv` should result in `six` being installed since it is required. 

Suspected problem: the rubyenv package does not list `six` as a dependency / requirement even though it imports it.

**Comment by lestephane** [comment]
Tried to work around the problem with

```bash
pip install six
```

But then

```bash
rubyenv install 2.4.2
```

causes the error

```text
Traceback (most recent call last):
  File ".../.virtualenvs/.../bin/rubyenv", line 6, in <module>
    from rubyenv import main
  File ".../.virtualenvs/.../lib/python3.7/site-packages/rubyenv/__init__.py", line 8, in <module>
    from .app import main
  File "/.../.virtualenvs/.../lib/python3.7/site-packages/rubyenv/app.py", line 13, in <module>
    from past.builtins import basestring
ModuleNotFoundError: No module named 'past'

```

Which can't be installed at all

```bash
$ pip install past
Collecting past
  Could not find a version that satisfies the requirement past (from versions: )
No matching distribution found for past
```

Not a python expert, could it be that python 3 is simply not supported?

**Comment by lestephane** [comment]
I managed to resolve the dependency on `past` by installing `future` (?)

```text
$ pip install future
```

**Comment by lestephane** [comment]
So, in summary, in a fresh python 3 Virtualenv, I'd expect

```bash
$ pip install rubyenv
```

to result in the installation of `six` and `future` as well (if they are not installed already), because rubyenv requires them to run correctly.

**Comment by schinckel** [comment]
Yeah, those should be declared as dependencies.

**Comment by USSX-Hares** [comment]
Fixed with #6
