### ISSUE TITLE
No module named 'past'

### ISSUE THREAD

**Issue by ikus060** [twang817/rubyenv#9]
When running `rubyenv`, python complain about `past` missing

```
Traceback (most recent call last):
  File "/home/ikus060/workspace/PDSL/cmdb.git/.tox/bootstrapemail/bin/rubyenv", line 5, in <module>
    from rubyenv import main
  File "/home/ikus060/workspace/PDSL/cmdb.git/.tox/bootstrapemail/lib/python3.9/site-packages/rubyenv/__init__.py", line 8, in <module>
    from .app import main
  File "/home/ikus060/workspace/PDSL/cmdb.git/.tox/bootstrapemail/lib/python3.9/site-packages/rubyenv/app.py", line 13, in <module>
    from past.builtins import basestring
ModuleNotFoundError: No module named 'past'
```

**Comment by ikus060** [comment]
Need to manually install `future` to get it fixed
